# Setup
title:               "Discrete Mathematics for Computer Science"
description:         'Discrete Mathematics for Computer Science - IUH'
url:                 https://nglelinh.github.io
baseurl:             '/discrete-mathematics-for-computer-science-iuh'
imgurl:              https://nglelinh.github.io/discrete-mathematics-for-computer-science-iuh/img
paginate:            5
permalink:           pretty

# Multi-language support
languages:           ["en", "vi"]
default_lang:        "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

# Language-specific configurations
t:
  en:
    title: "Discrete Mathematics for Computer Science"
    description: "Discrete Mathematics for Computer Science - IUH"
    home: "Home"
    chapters: "Chapters"
    language: "Language"
    switch_language: "Switch to Vietnamese"
    required: "Required"
    optional: "Optional"
  vi:
    title: "Toán Rời Rạc cho Khoa học Máy tính"
    description: "Toán Rời Rạc cho Khoa học Máy tính - IUH"
    home: "Trang chủ"
    chapters: "Các chương"
    language: "Ngôn ngữ"
    switch_language: "Chuyển sang tiếng Anh"
    required: "Bắt buộc"
    optional: "Tùy chọn"
# About/contact
author:
  name:              Nguyen Le Linh
  email:             nglelinh@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

plugins_dir: _plugins

# Collections for multilingual content
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Custom vars
version:             0.0.1
markdown: kramdown

# Analytics
google_analytics_id: ""
